### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by Gobleizer** [RFP-58-DK/SDC-Products#5]
https://github.com/RFP-58-DK/SDC-Products/blob/08b760ebf698148abfca4ba408bc6a99a337a86f/controller/index.js#L8

How are your handling your errors? Sending the information does not count as error handling. What is the appropriate response to a request when an error is encountered?

How would this affect your Stress testing?

**Comment by granchez77** [comment]
Fixed error handling.
